jobs:

# jobs for the sample node app pipeline from CI thru TEST environment

################################

# add pipeline workflow

# manifest gen for VISUALIZER
  - name: man-sample
    type: manifest
    steps:
      - IN: img-sample
      - IN: img-opts-sample
      - IN: trigger-test-deploy-sample
      - TASK: managed

# deploy visualizer to TEST

# TEST deployment for sample app to Google GKE
  - name: test-gke-sample
    type: deploy
    steps:
      - IN: man-sample
      - IN: env-test-gke
      - TASK: managed

# TEST deployment for sample app to Google GKE
  - name: prod-gke-sample
    type: deploy
    steps:
      - IN: test-gke-sample
        switch: off
#      - IN: img-opts-sample-prod
      - IN: trigger-prod-deploy-sample
      - IN: env-test-gke
      - TASK: managed
